language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      before_install:
        - export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=827536";
    - os: osx
      osx_image: xcode7.2 # macOS 10.11
      before_install:
        - brew update
        - brew install openssl
        - mkdir -p /usr/local/lib
        - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
        - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
        - export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=827533"
    
before_install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"

  # Install .NET CLI
  - mkdir $DOTNET_INSTALL_DIR
  - curl -L $DOTNET_SDK_URL -o dotnet_package
  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR

  # Add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
  # Display dotnet version info
  - dotnet --info
  - make build

script:
  - make tests
