language: csharp
mono: none
dotnet: 1.0.0-preview2-003131

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      before_install: 
        - brew update
        - brew install openssl
        - mkdir -p /usr/local/lib
        - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
        - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
install:
  - make build
script:
  - make tests
